spring:
  application:
    name: devoxxuk-26-koog
  datasource:
    url: jdbc:sqlite:server/.agent-fantasy-store/agent-fantasy-store.db
    driver-class-name: org.sqlite.JDBC
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-test}
    model:
      chat: openai
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
  exposed:
    generate-ddl: true

langfuse:
  url: ${LANGFUSE_BASE_URL:}
  publickey: ${LANGFUSE_PUBLIC_KEY:}
  secretkey: ${LANGFUSE_SECRET_KEY:}

